[package]
name = "blosc2-src"
version = "0.1.0"
edition = "2021"
build = "build.rs"
links = "blosc2"
license-file = "c-blosc2/LICENSE.txt"
exclude = [
    "c-blosc2/compat/**",
    "c-blosc2/tests/**",
    "c-blosc2/bench/**",
    "c-blosc2/internal-complibs/zlib-1.2.11/contrib/**",
    "c-blosc2/internal-complibs/zlib-1.2.11/examples/**",
    "c-blosc2/internal-complibs/zlib-1.2.11/doc/**",
    "c-blosc2/internal-complibs/zstd-1.5.2/legacy/**",
]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# run bindgen when building, requires llvm
bindgen = []

[dependencies]
cc = "1.0"

[build-dependencies]
bindgen = "0.65.1"
cc = "1.0"
